import { WebClient } from "@slack/web-api";
import { tool } from "ai";
import { z } from "zod";

interface SlackMessageResult {
  success: boolean;
  error: string | null;
  messageTs: string | null;
}

async function sendSlackMessage(
  channel: string,
  text: string,
  blocks?: Array<Record<string, unknown>>
): Promise<SlackMessageResult> {
  const token = process.env.SLACK_BOT_TOKEN;

  if (!token) {
    return {
      success: false,
      error: "SLACK_BOT_TOKEN is not configured",
      messageTs: null,
    };
  }

  const client = new WebClient(token);

  try {
    const result = await client.chat.postMessage({
      channel,
      text,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      blocks: blocks as any,
      unfurl_links: false,
      unfurl_media: false,
    });

    return {
      success: true,
      error: null,
      messageTs: result.ts || null,
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : "Failed to send message",
      messageTs: null,
    };
  }
}

function createPerformanceBlocks(
  summary: string,
  projectName?: string
): Array<Record<string, unknown>> {
  const now = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return [
    {
      type: "header",
      text: {
        type: "plain_text",
        text: `📊 Daily Performance Report${
          projectName ? ` - ${projectName}` : ""
        }`,
        emoji: true,
      },
    },
    {
      type: "context",
      elements: [
        {
          type: "plain_text",
          text: now,
        },
      ],
    },
    {
      type: "divider",
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: summary,
      },
    },
    {
      type: "divider",
    },
    {
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: "_Generated by Speed Insights Agent_ 🤖",
        },
      ],
    },
  ];
}

export const sendSlackNotificationTool = tool({
  description:
    "Sends a performance summary notification to a Slack channel. Use this after analyzing speed insights to notify the team about daily performance metrics.",
  parameters: z.object({
    summary: z
      .string()
      .describe(
        "The formatted performance summary to send. Should include key metrics, their ratings, and any recommendations."
      ),
    channel: z
      .string()
      .optional()
      .describe(
        "Slack channel ID to send to. If not provided, uses SLACK_CHANNEL_ID env var."
      ),
    projectName: z
      .string()
      .optional()
      .describe("Name of the project for the report header."),
  }),
  execute: async ({ summary, channel, projectName }) => {
    const targetChannel = channel || process.env.SLACK_CHANNEL_ID;

    if (!targetChannel) {
      return {
        success: false,
        error:
          "Slack channel is required. Provide it as parameter or set SLACK_CHANNEL_ID env var.",
        messageTs: null,
      };
    }

    const blocks = createPerformanceBlocks(summary, projectName);
    const plainText = `Daily Performance Report${
      projectName ? ` - ${projectName}` : ""
    }\n\n${summary}`;

    return await sendSlackMessage(targetChannel, plainText, blocks);
  },
});

export const sendSlackAlertTool = tool({
  description:
    "Sends an urgent alert to Slack when performance issues are detected. Use this for critical performance degradations.",
  parameters: z.object({
    issue: z
      .string()
      .describe("Description of the performance issue detected."),
    severity: z
      .enum(["warning", "critical"])
      .describe("Severity level of the alert."),
    metric: z.string().optional().describe("The specific metric affected."),
    value: z.number().optional().describe("The current value of the metric."),
    threshold: z
      .number()
      .optional()
      .describe("The threshold that was exceeded."),
    channel: z.string().optional().describe("Slack channel ID for the alert."),
  }),
  execute: async ({ issue, severity, metric, value, threshold, channel }) => {
    const targetChannel = channel || process.env.SLACK_CHANNEL_ID;

    if (!targetChannel) {
      return {
        success: false,
        error: "Slack channel is required",
        messageTs: null,
      };
    }

    const emoji = severity === "critical" ? "🚨" : "⚠️";
    const color = severity === "critical" ? "#dc3545" : "#ffc107";

    const blocks: Array<Record<string, unknown>> = [
      {
        type: "header",
        text: {
          type: "plain_text",
          text: `${emoji} Performance Alert`,
          emoji: true,
        },
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*Severity:* ${severity.toUpperCase()}\n\n${issue}`,
        },
      },
    ];

    if (metric && value !== undefined) {
      blocks.push({
        type: "section",
        fields: [
          {
            type: "mrkdwn",
            text: `*Metric:*\n${metric}`,
          },
          {
            type: "mrkdwn",
            text: `*Current Value:*\n${value}`,
          },
          ...(threshold !== undefined
            ? [
                {
                  type: "mrkdwn",
                  text: `*Threshold:*\n${threshold}`,
                },
              ]
            : []),
        ],
      });
    }

    const plainText = `${emoji} Performance Alert (${severity.toUpperCase()}): ${issue}`;

    return await sendSlackMessage(targetChannel, plainText, blocks);
  },
});
